default:
    symbol_consolidate:
        -   merge: BRK.A  # Low volume trades, excessive pricing, normally excluded in most indexes
            into: BRK.B
        -   merge: BRK-A  # Alt variation
            into: BRK-B
    volume:
        limit_min: 10000

indexes:
    top10-min10:
        sort_by: market_cap
        top: 10
        weight_min: 10

    top20-min5:
        sort_by: market_cap
        top: 20
        weight_min: 5

    top50-min2:
        sort_by: market_cap
        top: 50
        weight_min: 2

    top100-min1:
        sort_by: market_cap
        top: 100
        weight_min: 1

    top250-min0.4:
        sort_by: market_cap
        top: 250
        weight_min: 0.4

    top500-min0.2:
        sort_by: market_cap
        top: 500
        weight_min: 0.2

symbol_normalize:
    BRK-A: BRK.A
    BRK/A: BRK.A
    BRK-B: BRK.B
    BRK/B: BRK.B
    EBR-B: EBR.B
    EBR/B: EBR.B
    KIM-PN: KIM.PN
    KIM/PN: KIM.PNs
    MS-PQ: MS.PQ
    MS/PQ: MS.PQ
    PBR-A: PBR.A
    PBR/A: PBR.A
    RF-PF: RF.PF
    RF/PF: RF.PF
