import os
from pathlib import Path

COL_NAME = "name"
COL_MC = "market_cap"
COL_SYMBOL = "symbol"
COL_WEIGHT = "weighted"
COL_PRICE = "price"
COL_VOLUME = "volume"
COL_TYPE = "type"
COL_LIST_DATE = "list_date"

MIN_ULTRA_CAP = 1_000_000_000_000
MIN_MEGA_CAP = 200_000_000_000
MIN_LARGE_CAP = 10_000_000_000
MIN_MID_CAP = 2_000_000_000
MIN_SMALL_CAP = 300_000_000

API_CMC_TOKEN = os.getenv("CMC_API_TOKEN")
API_CMC_CACHE_ONLY = API_CMC_TOKEN is None
API_FMP_TOKEN = os.getenv("FMP_API_TOKEN")
API_FMP_CACHE_ONLY = API_FMP_TOKEN is None
API_POLY_TOKEN = os.getenv("POLY_API_TOKEN")
API_POLY_CACHE_ONLY = API_POLY_TOKEN is None

PATH_PROJECT_ROOT = Path(__file__).resolve().parents[1]
PATH_CONFIG = PATH_PROJECT_ROOT / "config.yaml"
PATH_DATA_ROOT = PATH_PROJECT_ROOT / "data"
PATH_DATA_CACHE_ROOT = PATH_DATA_ROOT / "cache"
PATH_DATA_SYMBOLS_ROOT = PATH_DATA_ROOT / "symbols"
PATH_INDEXES_ROOT = PATH_PROJECT_ROOT / "indexes"
PATH_LOGS_ROOT = PATH_PROJECT_ROOT / "logs"

PATH_DATA_ROOT.mkdir(parents=True, exist_ok=True)
PATH_DATA_CACHE_ROOT.mkdir(parents=True, exist_ok=True)
PATH_DATA_SYMBOLS_ROOT.mkdir(parents=True, exist_ok=True)
PATH_INDEXES_ROOT.mkdir(parents=True, exist_ok=True)
PATH_LOGS_ROOT.mkdir(parents=True, exist_ok=True)

ASSET_ADR_COMMON = "ADRC"
ASSET_COMMON_STOCK = "CS"
ASSET_CRYPTO = "CC"
ASSET_ORD_STOCK = "OS"
ASSET_TYPES = {ASSET_ADR_COMMON, ASSET_COMMON_STOCK, ASSET_CRYPTO, ASSET_ORD_STOCK}

FORM_STRUCT = "structured"
FORM_TEXT = "text"
